FROM apache/airflow:2.9.0

# Necessário ser root para instalar ferramentas de build (C++) que o PyTorch e Numpy podem exigir
USER root
RUN apt-get update \
  && apt-get install -y --no-install-recommends \
         build-essential \
  && apt-get autoremove -yqq --purge \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

# Volta para o usuário padrão do Airflow para evitar falhas de segurança e permissão
USER airflow

# Instala o gerenciador de dependências Poetry
RUN pip install --no-cache-dir poetry==1.8.2

# Define o local de trabalho do projeto de ML dentro do Airflow
WORKDIR /opt/airflow/project

# Copia TODOS os arquivos necessários para o Poetry instalar as dependências
COPY pyproject.toml poetry.lock README.md ./

# Desabilita ambientes virtuais (instala direto no python do Airflow) e instala tudo
RUN poetry config virtualenvs.create false \
    && poetry install --no-root --no-interaction --no-ansi

# Volta para o diretório raiz do Airflow para o inicializador padrão funcionar
WORKDIR /opt/airflow
